name: Build Crisis AI APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'app/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [ debug, release ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode keystore (release only)
        if: matrix.build-type == 'release'
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build APK (matrix)
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          if [ "${{ matrix.build-type }}" = "debug" ]; then
            ./gradlew assembleCrisisAIDebug --stacktrace
          else
            ./gradlew assembleCrisisAIRelease --stacktrace
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crisisAI-${{ matrix.build-type }}-apk
          path: |
            app/build/outputs/apk/crisisAI/${{ matrix.build-type }}/*.apk
          if-no-files-found: error

